apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-depl
  labels:
    app: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
     containers:
      - name: devops
        image: aldiaksrepo.azurecr.io/devops:15
        resources:
          requests:
            memory: "250Mi"
            cpu: "400m"
          limits:
            memory: "500Mi"
            cpu: "750m"
        ports:
        - containerPort: 5000
          name: service-port

---
apiVersion: v1
kind: Service
metadata:
  name: devopsservice
spec:
  selector:
    app: devops
  ports:
    - name: rest-port
      protocol: TCP
      targetPort: 5000
      port: 5000


